# Generated by Django 4.2.5 on 2023-09-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='source_link',
            new_name='project_link',
        ),
    ]
